CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS docs (
  id UUID PRIMARY KEY,
  title TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS doc_comments (
  id UUID PRIMARY KEY,
  doc_id UUID NOT NULL REFERENCES docs(id) ON DELETE CASCADE,
  author_name TEXT NOT NULL,
  from_pos INT NOT NULL,
  to_pos INT NOT NULL,
  text TEXT NOT NULL,
  resolved BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS doc_snapshots (
  doc_id UUID PRIMARY KEY REFERENCES docs(id) ON DELETE CASCADE,
  snapshot BYTEA NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS doc_updates (
  id BIGSERIAL PRIMARY KEY,
  doc_id UUID NOT NULL REFERENCES docs(id) ON DELETE CASCADE,
  update BYTEA NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);
